name: SomaGanesha
favicon: null
layout_spectrum: 0.23581
typography_spectrum: 0.571970400866121
title: SomaGanesha.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e0f12'
    - '#efd4b6'
    - '#6b544c'
    - '#998270'
    - '#b94b3e'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.9351551178842783
purpose: []
