name: SomaGanesha
favicon: null
layout_spectrum: 0.0270154292229563
typography_spectrum: 0.571970400866121
title: SomaGanesha.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.440813104622066
  lightness: 0.10175351682119071
  saturation: 0.32036895328201354
  rhythmicContrast: 0.9351551178842783
purpose: []
